"""Agent runtime orchestrator and smoke workflow.

The orchestrator wires planner -> executor -> reflector over an in-memory
run. The smoke workflow ``manual_jd_analysis_demo`` is deterministic and does
not require a model API key.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from app.agents.executor import PlaceholderExecutor
from app.agents.memory import InMemoryAgentMemory
from app.agents.planner import StaticPlanner
from app.agents.reflector import Reflector
from app.agents.runtime import (
    AgentRunData,
    AgentStepData,
    ArtifactData,
    ArtifactType,
    RunStatus,
    StepStatus,
)
from app.core.logging import get_logger
from app.models_gateway.base import ModelGateway
from app.models_gateway.fake import FakeModelGateway
from app.schemas.common import new_id

_log = get_logger(__name__)


class AgentOrchestrator:
    """Drives a single agent run through its planned steps."""

    def __init__(
        self,
        gateway: ModelGateway | None = None,
        planner: StaticPlanner | None = None,
        executor: PlaceholderExecutor | None = None,
        reflector: Reflector | None = None,
    ) -> None:
        self._gateway = gateway or FakeModelGateway()
        self._planner = planner or StaticPlanner()
        self._executor = executor or PlaceholderExecutor(self._gateway)
        self._reflector = reflector or Reflector()
        self._memory = InMemoryAgentMemory()

    async def run_workflow(self, workflow_type: str, context: dict[str, Any]) -> AgentRunData:
        run = AgentRunData(
            id=new_id("run"),
            workflow_type=workflow_type,
            status=RunStatus.running,
            started_at=datetime.now(UTC),
        )
        self._memory.remember("context", context)

        steps = self._planner.plan(workflow_type, context)
        for idx, planned in enumerate(steps, start=1):
            step: AgentStepData = await self._executor.execute(planned, run.id, idx, context)
            run.steps.append(step)
            decision = self._reflector.reflect(step)
            if decision == "fail":
                step.status = StepStatus.failed
                run.status = RunStatus.failed
                run.error = f"Step {step.name} failed"
                run.finished_at = datetime.now(UTC)
                _log.warning("agent.run_failed", run_id=run.id, step=step.name)
                return run

        run.status = RunStatus.succeeded
        run.finished_at = datetime.now(UTC)
        run.result = {"steps": len(run.steps)}
        _log.info("agent.run_succeeded", run_id=run.id, workflow=workflow_type)
        return run


async def manual_jd_analysis_demo(
    jd_text: str, gateway: ModelGateway | None = None
) -> tuple[AgentRunData, ArtifactData]:
    """Smoke workflow: produce a placeholder JD analysis artifact.

    Returns the run and the generated artifact. Deterministic; works without a
    model API key.
    """
    orchestrator = AgentOrchestrator(gateway=gateway)
    run = await orchestrator.run_workflow("manual_jd_analysis_demo", {"jd_text": jd_text})

    artifact = ArtifactData(
        id=new_id("art"),
        agent_run_id=run.id,
        artifact_type=ArtifactType.jd_analysis,
        prompt_version="demo-v1",
        model_name="fake-model",
        content="Placeholder JD analysis generated by the smoke workflow.",
        source_ids={"jd_excerpt": jd_text[:200]},
    )
    return run, artifact
